name: test

on: [push]

jobs:
  basic-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn run basic-test
        env:
          CI: true
          AIRTABLE_API_KEY: FAKE_KEY

  production-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version: 'latest'
      - run: yarn install --frozen-lockfile
      - run: yarn run production-test
        env:
          CI: true
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
